autoscaler formatting error fix
Change due to Error when using Autoscaler:
Error: Invalid expression                                                                                                                                               
│                                                                                                                                                                         
│   on kube.tf line 333, in module "kube-hetzner":                                                                                                                        
│  333:       taints      =                                                                                                                                               
│  334:       [{                                                                                                                                                          
│                                                                                                                                                                         
│ Expected the start of an expression, but found an invalid expression token.
Solution: 
1. change position of "[" and "]" bracket
2. change format of listed taints: key="value", not key:"value"